apiVersion: apps/v1
kind: DaemonSet  # 一种控制器 他所管理的po有如下特点，实际上是通过给pod加上nodeAffinity选择node实现的，同时，它还会自动给这个 Pod 加上一个 Toleration，从而忽略节点的 unschedulable“污点”
                  #      1.    这个pod运行在集群每一个节点上， 2每个节点只能运行一个， 3新加入的节点会自动部署这daemonpod
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system   
  labels:
    k8s-app: fluentd-logging
spec:
  selector:   # 所要管理的pod  ， 只管理一个pod daemonset没有 replicas属性
    matchLabels:
      name: fluentd-elasticsearch



  template:   # pod的定义，
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      tolerations:    # 容忍master节点自带的污点， 所以这个pod可以调度到master
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

      containers:    #  将容器内的日志复制到elasticsearch的功能
      - name: fluentd-elasticsearch
        image: k8s.gcr.io/fluentd-elasticsearch:1.20
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers