# 只要这个secret更新，使用他到他的容器里的数据会自动更新（有一定延时），由kubelete维护

apiVersion: v1
kind: Secret #是帮你把 Pod 想要访问的加密数据，存放到 Etcd 中。然后，你就可以通过在 Pod 的容器里挂载 Volume 的方式，访问到这些 Secret 里保存的信息了
metadata:
    name: mysecret
type: Opaque #不透明的
data: 
    user: YWRtaW4= # 值是经base64转码的， 投射到容器里的是解码后的数据
    pass: MWYyZDFlMmU2N2Rm