kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-rolebinding
  namespace: mynamespace  # 绑定role时只在mynamespace有效， role和rolebind namespace不同时以 rolebinding为准


subjects:  # 为 example-user
- kind: User
  name: example-user
  apiGroup: rbac.authorization.k8s.io
roleRef: # 绑定 example-role
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io