
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort  
  ports:
  - nodePort: 8080  # 宿主机的8080端口转发到他所代理的pod的80端口, DNAT 与SNAT实现
    targetPort: 80
    protocol: TCP
    name: http
  - nodePort: 443
    protocol: TCP
    name: https
  selector:
    run: my-nginx